services:
  database:
    image: postgres:15.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartnewstracker
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
volumes:
  postgres-data: